### ISSUE TITLE
Video on Homepage (mobile)

### ISSUE THREAD

**Issue by shapeshed** [pebblecode/pebblecode.github.io#102]
Need to work out what to do about the background video on mobile.

<img width="302" alt="screen shot 2016-06-17 at 13 49 56" src="https://cloud.githubusercontent.com/assets/33444/16151007/7920d1c2-3492-11e6-9b95-4bc8fa60fbe8.png">

**Comment by petertait** [comment]
Either static jpeg or gif alternative if we want to be funky. Although gif will be heavy to load.

**Comment by petertait** [comment]
https://github.com/pebblecode/pebblecode.github.io/pulls fixes this with use of a fallback image in replacement of the video as iOS doesn't allow autoplaying videos.
