### ISSUE TITLE
Header transparency

### ISSUE THREAD

**Issue by poshaughnessy** [pebblecode/pebblecode.github.io#105]
On the Health page, the header is opaque when you scroll down:

<img width="1035" alt="screen shot 2016-06-17 at 14 10 40" src="https://cloud.githubusercontent.com/assets/151207/16151526/62029c34-3495-11e6-8119-5f2a999422ea.png">

But towards the top, it's transparent, which makes the text clash:

<img width="1012" alt="screen shot 2016-06-17 at 14 10 48" src="https://cloud.githubusercontent.com/assets/151207/16151539/7061252a-3495-11e6-891a-090319ff770f.png">

Is that intentional?

**Comment by petertait** [comment]
This has been fixed now. There are a few other tweaks required but major bugs should be gone.

https://github.com/pebblecode/pebblecode.github.io/commit/edec387ac3018b56bdd570ca34162b8a3ab23b65
