### ISSUE TITLE
Placeholder image for blog posts

### ISSUE THREAD

**Issue by poshaughnessy** [pebblecode/pebblecode.github.io#106]
Featured blog posts that don't have images look a bit glaring. How about having a default placeholder image, like before?

<img width="855" alt="screen shot 2016-06-17 at 14 15 14" src="https://cloud.githubusercontent.com/assets/151207/16151619/efd3dcbc-3495-11e6-8eea-028042393a32.png">

<img width="1031" alt="screen shot 2016-06-17 at 14 15 44" src="https://cloud.githubusercontent.com/assets/151207/16151636/031c3224-3496-11e6-878d-cf270dfffbe8.png">

**Comment by petertait** [comment]
https://github.com/pebblecode/pebblecode.github.io/commit/6be26e5536eca1322284c556855a2f1f0940c3e4 has fixed this.
