### ISSUE TITLE
Video on iOS

### ISSUE THREAD

**Issue by elpabl0** [pebblecode/pebblecode.github.io#108]
I get a slightly different issue on iOS (iPhone 6, iOS 9.2.3, Chrome and Safari). Misaligned video play buttons, and the video doesn't actually work.
![img_1392](https://cloud.githubusercontent.com/assets/503173/16187761/f8307470-36c9-11e6-90f0-1b5270ab2314.PNG)

**Comment by petertait** [comment]
"Video plays, but 'play' button is still misaligned."

**Comment by petertait** [comment]
https://github.com/pebblecode/pebblecode.github.io/pulls fixes:
- Removal of duplicate play button
- Uses fallback image in replacement of the video as iOS doesn't allow autoplaying videos.
- Play button now plays video automatically without a second tap of the native play button.
