### ISSUE TITLE
blog.pebblecode.com

### ISSUE THREAD

**Issue by tobyhunt** [pebblecode/pebblecode.github.io#12]
Still goes to Tumblr. DNS needs updating to point:

blog.pebblecode.com --> pebblecode.com/blog

**Comment by tobyhunt** [comment]
@shapeshed - any reason not to update this? Don't think so but thought I would check.

**Comment by shapeshed** [comment]
It is not possible. Github doesn't support multiple CNAMES so we can't do
it '-(

**Comment by tobyhunt** [comment]
But if we could we would right? Will set up another redirect. 

## 

Toby Hunt
Director & Co-founder 
pebble {code}

Mobile # +44 (0) 7977 012 959
Office # +44 (0) 20 3327 3940

http://pebblecode.com

**Comment by shapeshed** [comment]
Traffic is going via a proxy server now to get round only one CNAME being supported in Github pages.

```
server {
    server_name blog.pebblecode.com;
    rewrite ^ http://pebblecode.com$request_uri? permanent;
}
```
