### ISSUE TITLE
Blog Improvements

### ISSUE THREAD

**Issue by petertait** [pebblecode/pebblecode.github.io#13]
- Use categories to create collections of articles such as Lightning Talks. We can then start to create custom templates for Lightning Talks and a section within the Blog area just for Lightning Talks (and other types of collections).
- Look at fine tuning the design of images/videos in blog posts and start using captions.
- Spice up the blog homepage so there is more than just a list of articles. Maybe use the collections in a grid format with images for each followed by the list of all articles below. Or just look at alternative layouts for displaying blog posts.
- Add a relevant post section at bottom of blog article pages. This means blog posts need to have properly labelled and reusable categories, rather than a list of new tags for each article.

**Comment by markdurrant** [comment]
Moved to Trello for ideas tracking.
