### ISSUE TITLE
Better access to navigation on internal pages

### ISSUE THREAD

**Issue by eliachoc** [pebblecode/pebblecode.github.io#15]
Some internal pages involve quite a bit of scrolling to get back to the top to access main navigation.

Maybe either make sticky navigation appear on scroll top, or create a 'back to top' button at the end of the page. 

Thoughts?

**Comment by petertait** [comment]
Sounds good, would be cool to see mockups of both. Especially see this being useful on smaller/mobile devices – may mean that the header markup will need tweaking to suit a fixed style.

**Comment by petertait** [comment]
Show/hide header has long been implemented!
