### ISSUE TITLE
Call to action text

### ISSUE THREAD

**Issue by shapeshed** [pebblecode/pebblecode.github.io#81]
Is it me or does the call to action text feel a bit pimp down the back of an alley? If there is any agreement let's remove it. 

<img width="551" alt="screen shot 2016-04-25 at 17 42 22" src="https://cloud.githubusercontent.com/assets/33444/14791295/318d5ac8-0b0d-11e6-99da-d7d1d0441730.png">

**Comment by bkspace** [comment]
I don't think it's too 'back alley'-ish, but I do think it's probably a bad CTA?

'Want to transform your innovative capacity?' 
'Find out how we can improve your digital workflow'

**Comment by petertait** [comment]
Update made to the copy: https://github.com/pebblecode/pebblecode.github.io/commit/cd46f6c8463385061e8e5bb8629f54e329146733

**Comment by petertait** [comment]
No longer required.
