### ISSUE TITLE
404 - 'Webmaster'

### ISSUE THREAD

**Issue by elpabl0** [pebblecode/pebblecode.github.io#94]
Page currently suggests getting in contact with 'your webmaster' in a couple of places. Shouldn't this be 'our webmaster'?

**Comment by petertait** [comment]
Fixed: https://github.com/pebblecode/pebblecode.github.io/commit/178d18efe0ea4d24d24684a883ba2798ff4ede73

**Comment by elpabl0** [comment]
Video plays, but 'play' button is still misaligned.

**Comment by petertait** [comment]
Wrong issue?

Mixed up with this: https://github.com/pebblecode/pebblecode.github.io/issues/108

**Comment by petertait** [comment]
issue mixup, this one is squashed.
